---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  argocd-image-updater.argoproj.io/write-back-method: argocd
  argocd-image-updater.argoproj.io/app2.update-strategy: latest
  argocd-image-updater.argoproj.io/image-list: app1=app1
  argocd-image-updater.argoproj.io/app1.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    repoURL: https://github.com/luca-iachini/argocd-test.git
    targetRevision: HEAD
    path: kustomize/base/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
