apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    repoURL: https://github.com/luca-iachini/argocd-test.git
    targetRevision: HEAD
    path: kustomize/base/app2
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true