apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-go
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: go
          image: app1:latest
          imagePullPolicy: "Always"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 300"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
