apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: git-difference
spec:
  serviceAccountName: workflow
  templates:
    - name: git-difference
      inputs:
        parameters:
          - name: message
          - name: repo_owner
          - name: repo_name
      script:
        image: makocchi/alpine-git-curl-jq:latest
        command: [sh]
        source: |
          git clone https://github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}.git
          cd {{inputs.parameters.repo_name}}
          packages=$(git log --format= -n 1 --name-only | sed -E 's/^go\/(.*)\/.*$/\1/' | sort | uniq)
          json=""
          for package in $packages
          do
            [ ! -z "$package" ] && json="$json\"$package\","
          done
          echo "[${json::-1}]" > /mnt/out/packages
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      outputs:
        parameters:
        - name: packages
          valueFrom:
            path: /mnt/out/packages
      volumes:
        - name: out
          emptyDir: { }