apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: git-clone
spec:
  serviceAccountName: workflow
  templates:
    - name: git-clone
      inputs:
        parameters:
          - name: repo_owner
          - name: repo_name
        artifacts:
        - name: git-source
          path: /mnt/out/src
          git:
            repo: https://github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}.git
            usernameSecret:
              name: github-access
              key: user
            passwordSecret:
              name: github-access
              key: token
      script:
        image: makocchi/alpine-git-curl-jq:latest
        command: [sh]
        workingDir: /mnt/out/src
        source: |
          packages=$(git log --format= -n 1 --name-only | sed -nE 's/^go\/(.*)\/.*$/\1/p' | sort | uniq)
          ls -la
          echo $packages
          json=""
          for package in $packages
          do
            [ ! -z "$package" ] && json="$json\"$package\","
          done
          echo "[${json::-1}]" > /mnt/out/packages
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      outputs:
        parameters:
        - name: packages
          valueFrom:
            path: /mnt/out/packages
        artifacts:
          - name: git-source
            path: /mnt/out/src
      volumes:
        - name: out
          emptyDir: { }