apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  generateName: webhook-
  name: pipeline
spec:
  entrypoint: pipeline
  serviceAccountName: workflow
  arguments:
    parameters:
      - name: version
  templates:
    - name: pipeline
      dag:
        tasks:
          - name: git-difference
            templateRef:
              name: git-difference
              template: git-difference
              clusterScope: true
            arguments:
              parameters:
                - name: message
                  value: "{}"
                - name: repo_owner
                  value: "luca-iachini"
                - name: repo_name
                  value: "argocd-test"
          - name: test
            templateRef:
              name: test
              template: test
              clusterScope: true
            arguments:
              parameters:
                - name: package
                  value: "{{item}}"
            withParam: "{{tasks.git-difference.outputs.parameters.packages}}"
            dependencies:
              - git-difference
          - name: build
            templateRef:
              name: build
              template: build
              clusterScope: true
            arguments:
              parameters:
                - name: package
                  value: "{{item}}"
            withParam: "{{tasks.git-difference.outputs.parameters.packages}}"
            dependencies:
              - test
          - name: promote
            templateRef:
              name: promote
              template: promote
              clusterScope: true
            arguments:
              parameters:
                - name: packages
                  value: "{{tasks.git-difference.outputs.parameters.packages}}"
                - name: repo_owner
                  value: "luca-iachini"
                - name: repo_name
                  value: "argocd-test"
                - name: version
                  value: "{{workflow.parameters.version}}"
            dependencies:
              - build