apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pipeline
  generateName: webhook-
spec:
  entrypoint: pipeline
  serviceAccountName: workflow
  parallelism: 2
  arguments:
    parameters:
      - name: version
        value: 1.0.0
      - name: repo_owner
        value: test
      - name: repo_name
        value: test
  templates:
    - name: pipeline
      steps:
        - - name: git-clone
            templateRef:
              name: git-clone
              template: git-clone
              clusterScope: true
            arguments:
              parameters:
                - name: "repo_owner"
                  value: "{{workflow.parameters.repo_owner}}"
                - name: "repo_name"
                  value: "{{workflow.parameters.repo_name}}"
        - - name: test
            templateRef:
              name: test
              template: test
              clusterScope: true
            arguments:
              parameters:
                - name: package
                  value: "{{item}}"
            withParam: "{{steps.git-clone.outputs.parameters.packages}}"
        - - name: build
            templateRef:
              name: build
              template: build
              clusterScope: true
            arguments:
              parameters:
                - name: package
                  value: "{{item}}"
            withParam: "{{steps.git-clone.outputs.parameters.packages}}"
        - - name: promote
            templateRef:
              name: promote
              template: promote
              clusterScope: true
            arguments:
              parameters:
                - name: version
                  value: "{{workflow.parameters.version}}"
                - name: packages
                  value: "{{steps.git-clone.outputs.parameters.packages}}"
              artifacts:
                - name: "git-source"
                  from: "{{steps.git-clone.outputs.artifacts.git-source}}"
