apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  generateName: webhook-
  name: pipeline
spec:
  entrypoint: pipeline
  serviceAccountName: workflow
  parallelism: 2
  arguments:
    parameters:
      - name: version
        value: 0.0.1
  templates:
    - name: pipeline
      steps:
        - - name: git-difference
            templateRef:
              name: git-difference
              template: git-difference
              clusterScope: true
            arguments:
              parameters:
                - name: message
                  value: "{}"
                - name: repo_owner
                  value: "luca-iachini"
                - name: repo_name
                  value: "argocd-test"
        - - name: test
            templateRef:
              name: test
              template: test
              clusterScope: true
            arguments:
              parameters:
                - name: package
                  value: "{{item}}"
            withParam: "{{steps.git-difference.outputs.parameters.packages}}"
        - - name: build
            templateRef:
              name: build
              template: build
              clusterScope: true
            arguments:
              parameters:
                - name: package
                  value: "{{item}}"
            withParam: "{{steps.git-difference.outputs.parameters.packages}}"
        - - name: promote
            templateRef:
              name: promote
              template: promote
              clusterScope: true
            arguments:
              parameters:
                - name: packages
                  value: "{{steps.git-difference.outputs.parameters.packages}}"
                - name: repo_owner
                  value: "luca-iachini"
                - name: repo_name
                  value: "argocd-test"
                - name: version
                  value: "{{workflow.parameters.version}}"