apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: promote
spec:
  serviceAccountName: workflow
  templates:
    - name: promote
      inputs:
        parameters:
          - name: packages
          - name: repo_owner
          - name: repo_name
          - name: version
      script:
        image: smartive/kustomize:latest
        command: [sh]
        source: |
          echo "promoting package {{inputs.parameters.packages}}"
          set -e
          git clone https://$(cat /.github/token)@github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}
          cd {{inputs.parameters.repo_name}}
          git config user.name "$(cat /.github/user)"
          git config user.email "$(cat /.github/email)"
          packages=$(echo "{{inputs.parameters.packages}}" | sed 's/[][",]/ /g' | sed 's/  */ /g | sed 's/ /\n/g')
          for package in $packages
          do
            if [ ! -z "$package" ]; then
              cd kustomize/base/$package
              kustomize edit set image $package=$package:{{inputs.parameters.version}}
              git add .
            fi
          done
          git commit -m "Upgrade applications to {{inputs.parameters.version}}"
          git push
        volumeMounts:
        - name: github-access
          mountPath: /.github/
      volumes:
        - name: github-access
          secret:
            secretName: github-access
            items:
              - key: token
                path: token
              - key: email
                path: email
              - key: user
                path: user