apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: test
spec:
  serviceAccountName: workflow
  templates:
    - name: test
      inputs:
        parameters:
          - name: package
            value: "test"
      outputs:
        parameters:
          - name: package
            value: "{{input.parameters.package}}"
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo "building package {{inputs.parameters.package}}"