apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
    policy.csv: |
      p, role:image-updater, applications, get, */*, allow
      p, role:image-updater, applications, update, */*, allow
      g, image-updater, role:image-updater