apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  generateName: webhook-
  name: build-pipeline
spec:
  entrypoint: pipeline
  serviceAccountName: workflow
  templates:
    - name: pipeline
      dag:
        tasks:
          - name: git-difference
            template: git-difference
            arguments:
              parameters:
                - name: message
                  value: "{}"
                - name: repo_owner
                  value: "luca-iachini"
                - name: repo_name
                  value: "argocd-test"
          - name: build
            template: build
            arguments:
              parameters:
                - name: package
                  value: "{{item}}"
            withParam: "{{tasks.git-difference.outputs.result}}"
            dependencies:
              - git-difference
    - name: git-difference
      inputs:
        parameters:
          - name: message
          - name: repo_owner
          - name: repo_name
      script:
        image: makocchi/alpine-git-curl-jq:latest
        command: [sh]
        source: |
          git clone https://github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}.git > /dev/null
          cd {{inputs.parameters.repo_name}}
          packages=$(git log --format= -n 1 --name-only | sed -nE 's/^go\/(.*)\/.*$/\1/p' | sort | uniq)
          echo -n '['
          last=$(echo $packages | tail -n 1)
          echo $packages | while read package; do
            echo -n "\"$package\""
            if [ "$package" != "$last" ]; then
              echo -n ","
            fi
          done
          echo ']'
    - name: build
      inputs:
        parameters:
          - name: package
      script:
        image: makocchi/alpine-git-curl-jq:latest
        command: [sh]
        source: |
          echo {{inputs.parameters.package}}