---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  serviceAccountName: workflow
  templates:
    - name: build-kaniko
      inputs:
        parameters:
          - name: package
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo "building {{inputs.parameters.package}}"
