apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - github.com/argoproj/argo-workflows/manifests/base
  - github.com/argoproj/argo-workflows/manifests/cluster-install/workflow-controller-rbac
  - github.com/argoproj/argo-workflows/manifests/cluster-install/argo-server-rbac
  - rbac.yaml
  - ingress.yaml
  - workflows/pipeline-workflow.yaml
  - workflows/git-difference-workflow.yaml
  - workflows/build-workflow.yaml
  - workflows/test-workflow.yaml
  - workflows/promote-workflow.yaml
patchesStrategicMerge:
  - config.yaml
  - server-deployment.yaml
namespace: argo
