apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  template:
    spec:
      containers:
        - name: argo-server
          env:
            - name: ARGO_SECURE
              value: "false"
            - name: ARGO_HTTP1
              value: "true"
          args: ["server", "--basehref", "/argo/"]
          readinessProbe:
            httpGet:
              scheme: HTTP
