apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - github.com/argoproj/argo-events/manifests/base
  - event-bus.yaml
  - event-sources.yaml
  #- example-sensor.yaml
  - push-sensor.yaml
namespace: argo-events
