apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-push
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: webhook-push-dep
      eventSourceName: webhook
      eventName: push
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: git-difference
                arguments:
                  parameters:
                    - name: message
                      value: '{"packets": []}'
                    - name: repo_owner
                      value: luca-iachini
                    - name: repo_name
                      value: argocd-test
                templates:
                  - name: git-difference
                    inputs:
                      parameters:
                        - name: message
                        - name: repo_owner
                        - name: repo_name
                    script:
                      image: makocchi/alpine-git-curl-jq:latest
                      command: [sh]
                      source: |
                        git clone https://github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}.git
                        cd {{inputs.parameters.repo_name}}
                        PACKAGES=$(git log --format= -n 1 --name-only | pcregrep -o1 "^go\/(.*?)\/.*" | sort | uniq)
                        echo $PACKAGES
                        for package in $PACKAGES
                          curl -X POST -d '{"package": "$package"}' http://webhook-eventsource-svc:13000/start
                        do
                        done
          parameters:
            - src:
                dependencyName: push
              dest: spec.arguments.parameters.0.value
