apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-push
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: webhook-push-dep
      eventSourceName: webhook
      eventName: push
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          kind: Workflow
          operation: resubmit
          metadata:
            generateName: push-build-pipeline-
          spec:
            serviceAccountName: workflow
            entrypoint: pipeline
            workflowTemplateRef:
              name: build-pipeline
              clusterScope: true