apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-push
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: webhook-push-dep
      eventSourceName: webhook
      eventName: push
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          parameters:
          - src:
              dependencyName: webhook-push-dep
              dataKey: body.version
            dest: spec.arguments.parameters.0.value
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: push-trigger-
                namespace: argo
              spec:
                arguments:
                  parameters:
                    - name: version
                    - name: repo_owner
                      value: luca-iachini
                    - name: repo_name
                      value: argocd-test
                entrypoint: pipeline
                serviceAccountName: workflow
                workflowTemplateRef:
                  name: pipeline
                  clusterScope: true